[package]
name = "convex-hypervisor"
version = "0.1.0"
edition = "2021"

[dependencies]
convex-shared = { path = "../shared" }
goblin = { version = "0.9", default-features = false, features = ["elf32", "elf64", "endian_fd"] }
libc = "0.2"
rand = { version = "0.8", default-features = false }
rand_chacha = "0.3"
vm-fdt = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
kvm-ioctls = "0.19"
kvm-bindings = { version = "0.10", features = ["fam-wrappers"] }
